### ISSUE TITLE
Looking forward to new content

### ISSUE THREAD

**Issue by TanNgocDo** [rust-cloud-native/core#2]
This repo is very promising. Looking forward to new content

**Comment by nickgerace** [comment]
Thank you @TanNgocDo! We have launched today: https://nickgerace.dev/launching-rust-cloud-native

**Comment by nickgerace** [comment]
Check out our discussions:
- https://github.com/rust-cloud-native/rust-cloud-native.github.io/discussions/24
- https://github.com/rust-cloud-nativecore/discussions/24
